### ISSUE TITLE
S3 key not existing (race condition)?

### ISSUE THREAD

**Issue by troydieter** [aws-samples/amazon-textract-and-amazon-comprehend-medical-claims-example#2]
Hi, 

[Hitting the following](https://snipboard.io/dG32kQ.jpg) when attempting to execute the stack. I thought it was a race-condition and added a `DependsOn` to the S3 bucket, but that is not the issue. Thoughts?

**Comment by jetulis** [comment]
I solved this issue by running the stack with lambda commented out so it created buckets with zip files . then updated the stack to create the rest of resources.

**Comment by jetulis** [comment]
I don't see quicksights , athena related info while diagram has them.

**Comment by troydieter** [comment]
> I solved this issue by running the stack with lambda commented out so it created buckets with zip files . then updated the stack to create the rest of resources.

I meant to update this, I fixed it in a few spots. [Refer to this for more info.](https://github.com/troydieter/aws-textract-comprehend)
